### ISSUE TITLE
mono_assembly_foreach cannot be found by  Module.findExportByName

### ISSUE THREAD

**Issue by hcleldaddonio** [freehuntx/frida-mono-api#5]
Hey,

When trying to use the API you provide I notice that exception is being thrown.
After small debugging, I figure out that mono_assembly_foreach  cannot be found by Module.findExportByName - it returns null.
do you know that reason?
I tried this for an iOS Xamarin app but no luck.

**Comment by freehuntx** [comment]
Sorry for the late answer.
Can you check that again?
I merged some changes which may fix that.

**Comment by hcleldaddonio** [comment]
Nope, it still doesn't work.
Did you try on a device or simulator?

Can you share details regarding the app you perform your tests with?

**Comment by freehuntx** [comment]
I dont work with xamarin and dont plan to but i guess thats a issue with non existent api exports.
I guess its related to this issue: https://github.com/freehuntx/frida-mono-api/issues/3

**Comment by freehuntx** [comment]
Im currently reworking "frida-mono" and it will contain everything needed to work with mono.
This repo will become obsolete when thats done.
You can follow the current state in this branch: https://github.com/freehuntx/frida-mono/tree/feature/v1

I wont concentrate on fixing things here since im not happy with the codebase.
Keep an eye on frida-mono :)
